// 200 Mohalla / Wards / Micro-Areas of Lucknow
import { LucknowLocation } from './lucknow-types'

// Central Lucknow Mohallas
export const centralMohallas: LucknowLocation[] = [
  { id: 'nadan-mahal', name: 'Nadan Mahal', slug: 'nadan-mahal', type: 'area', description: 'Historic area in Central Lucknow', propertyTypes: ['2BHK', '3BHK', 'Shop'], nearbyLandmarks: ['Hazratganj'], popular: false },
  { id: 'qaiserbagh-mohalla', name: 'Qaiserbagh Mohalla', slug: 'qaiserbagh-mohalla', type: 'area', description: 'Heritage mohalla near Kaiserbagh', propertyTypes: ['2BHK', 'Shop'], nearbyLandmarks: ['Kaiserbagh'], popular: false },
  { id: 'nazirabad', name: 'Nazirabad', slug: 'nazirabad', type: 'area', description: 'Traditional residential area', propertyTypes: ['1BHK', '2BHK'], nearbyLandmarks: ['Hazratganj'], popular: false },
  { id: 'maulvi-ganj', name: 'Maulvi Ganj', slug: 'maulvi-ganj', type: 'area', description: 'Historic commercial area', propertyTypes: ['Shop', '1BHK'], nearbyLandmarks: ['Aminabad'], popular: false },
  { id: 'khayali-ganj', name: 'Khayali Ganj', slug: 'khayali-ganj', type: 'area', description: 'Traditional mohalla', propertyTypes: ['1BHK', '2BHK'], nearbyLandmarks: ['Chowk'], popular: false },
  { id: 'bans-mandi', name: 'Bans Mandi', slug: 'bans-mandi', type: 'area', description: 'Commercial area', propertyTypes: ['Shop', 'Commercial'], nearbyLandmarks: ['Chowk'], popular: false },
  { id: 'rakabganj', name: 'Rakabganj', slug: 'rakabganj', type: 'area', description: 'Traditional area', propertyTypes: ['1BHK', '2BHK', 'Shop'], nearbyLandmarks: ['Hazratganj'], popular: false },
  { id: 'bapu-nagar', name: 'Bapu Nagar', slug: 'bapu-nagar', type: 'area', description: 'Residential mohalla', propertyTypes: ['2BHK', '3BHK'], nearbyLandmarks: ['Hazratganj'], popular: false },
  { id: 'latouche-road', name: 'Latouche Road', slug: 'latouche-road', type: 'area', description: 'Premium area', propertyTypes: ['2BHK', '3BHK', 'Villa'], nearbyLandmarks: ['Hazratganj'], popular: false },
  { id: 'wazirganj-mohalla', name: 'Wazirganj Mohalla', slug: 'wazirganj-mohalla', type: 'area', description: 'Central mohalla', propertyTypes: ['2BHK', 'Shop'], nearbyLandmarks: ['Hazratganj'], popular: false },
  { id: 'naka-hindola', name: 'Naka Hindola', slug: 'naka-hindola', type: 'area', description: 'Junction area', propertyTypes: ['Shop', '2BHK'], nearbyLandmarks: ['Hazratganj'], popular: false },
  { id: 'hussainganj-mohalla', name: 'Hussainganj Mohalla', slug: 'hussainganj-mohalla', type: 'area', description: 'Central mohalla', propertyTypes: ['2BHK', 'Shop'], nearbyLandmarks: ['Hazratganj'], popular: false },
  { id: 'charbagh-mohalla', name: 'Charbagh Mohalla', slug: 'charbagh-mohalla', type: 'area', description: 'Area near railway station', propertyTypes: ['PG', '1BHK', 'Shop'], nearbyLandmarks: ['Charbagh'], popular: false },
  { id: 'daliganj-mohalla', name: 'Daliganj Mohalla', slug: 'daliganj-mohalla', type: 'area', description: 'Traditional mohalla', propertyTypes: ['1BHK', '2BHK'], nearbyLandmarks: ['Daliganj'], popular: false },
  { id: 'bawarchi-tola', name: 'Bawarchi Tola', slug: 'bawarchi-tola', type: 'area', description: 'Historic area', propertyTypes: ['1BHK', 'Shop'], nearbyLandmarks: ['Chowk'], popular: false },
  { id: 'machchi-bhawan', name: 'Machchi Bhawan', slug: 'machchi-bhawan', type: 'area', description: 'Historic area', propertyTypes: ['Shop', '1BHK'], nearbyLandmarks: ['Chowk'], popular: false },
  { id: 'aminabad-mohalla', name: 'Aminabad Mohalla', slug: 'aminabad-mohalla', type: 'area', description: 'Famous market area', propertyTypes: ['Shop', 'Commercial'], nearbyLandmarks: ['Aminabad'], popular: true },
  { id: 'chowk-sarafa', name: 'Chowk Sarafa', slug: 'chowk-sarafa', type: 'area', description: 'Jewelry market area', propertyTypes: ['Shop', 'Commercial'], nearbyLandmarks: ['Chowk'], popular: false },
  { id: 'gol-darwaza', name: 'Gol Darwaza', slug: 'gol-darwaza', type: 'area', description: 'Historic gate area', propertyTypes: ['Shop', '1BHK'], nearbyLandmarks: ['Chowk'], popular: false },
  { id: 'victoria-street-mohalla', name: 'Victoria Street Mohalla', slug: 'victoria-street-mohalla', type: 'area', description: 'Central area', propertyTypes: ['Shop', '2BHK'], nearbyLandmarks: ['Hazratganj'], popular: false },
  { id: 'anand-nagar', name: 'Anand Nagar', slug: 'anand-nagar', type: 'area', description: 'Residential area', propertyTypes: ['2BHK', '3BHK'], nearbyLandmarks: ['Hazratganj'], popular: false },
  { id: 'old-hyderabad-mohalla', name: 'Old Hyderabad Mohalla', slug: 'old-hyderabad-mohalla', type: 'area', description: 'Historic mohalla', propertyTypes: ['1BHK', '2BHK'], nearbyLandmarks: ['Chowk'], popular: false },
  { id: 'nakkhas', name: 'Nakkhas', slug: 'nakkhas', type: 'area', description: 'Traditional market area', propertyTypes: ['Shop', '1BHK'], nearbyLandmarks: ['Chowk'], popular: false },
  { id: 'shah-mina-road', name: 'Shah Mina Road', slug: 'shah-mina-road', type: 'area', description: 'Commercial area', propertyTypes: ['Shop', '2BHK'], nearbyLandmarks: ['Aminabad'], popular: false },
  { id: 'phool-mandi', name: 'Phool Mandi', slug: 'phool-mandi', type: 'area', description: 'Flower market area', propertyTypes: ['Shop', '1BHK'], nearbyLandmarks: ['Chowk'], popular: false },
]

// East Lucknow Mohallas (Gomti Nagar, Indira Nagar)
export const eastMohallas: LucknowLocation[] = [
  { id: 'nehru-enclave', name: 'Nehru Enclave', slug: 'nehru-enclave', type: 'area', description: 'Premium enclave', propertyTypes: ['2BHK', '3BHK', 'Villa'], nearbyLandmarks: ['Gomti Nagar'], popular: true },
  { id: 'patrakarpuram-mohalla', name: 'Patrakarpuram', slug: 'patrakarpuram-mohalla', type: 'area', description: 'Residential area in Gomti Nagar', propertyTypes: ['2BHK', '3BHK'], nearbyLandmarks: ['Gomti Nagar'], popular: true },
  { id: 'vijayant-khand', name: 'Vijayant Khand', slug: 'vijayant-khand', type: 'area', description: 'Sector in Gomti Nagar', propertyTypes: ['2BHK', '3BHK'], nearbyLandmarks: ['Gomti Nagar'], popular: false },
  { id: 'vibhuti-khand', name: 'Vibhuti Khand', slug: 'vibhuti-khand', type: 'area', description: 'Sector in Gomti Nagar', propertyTypes: ['2BHK', '3BHK'], nearbyLandmarks: ['Gomti Nagar'], popular: false },
  { id: 'viraj-khand', name: 'Viraj Khand', slug: 'viraj-khand', type: 'area', description: 'Sector in Gomti Nagar', propertyTypes: ['2BHK', '3BHK'], nearbyLandmarks: ['Gomti Nagar'], popular: false },
  { id: 'manas-enclave', name: 'Manas Enclave', slug: 'manas-enclave', type: 'area', description: 'Residential enclave', propertyTypes: ['2BHK', '3BHK', 'Villa'], nearbyLandmarks: ['Gomti Nagar'], popular: false },
  { id: 'lekhraj-market-area', name: 'Lekhraj Market Area', slug: 'lekhraj-market-area', type: 'area', description: 'Commercial area', propertyTypes: ['Shop', '2BHK'], nearbyLandmarks: ['Indira Nagar'], popular: false },
  { id: 'munshi-pulia-mohalla', name: 'Munshi Pulia Mohalla', slug: 'munshi-pulia-mohalla', type: 'area', description: 'Junction area', propertyTypes: ['Shop', '2BHK', 'PG'], nearbyLandmarks: ['Munshi Pulia'], popular: true },
  { id: 'ismailganj', name: 'Ismailganj', slug: 'ismailganj', type: 'area', description: 'Residential area', propertyTypes: ['2BHK', '3BHK'], nearbyLandmarks: ['Indira Nagar'], popular: false },
  { id: 'polytechnic-mohalla', name: 'Polytechnic Mohalla', slug: 'polytechnic-mohalla', type: 'area', description: 'Area near Polytechnic', propertyTypes: ['PG', '2BHK'], nearbyLandmarks: ['Polytechnic Chauraha'], popular: false },
  { id: 'faizabad-road-mohalla', name: 'Faizabad Road Mohalla', slug: 'faizabad-road-mohalla', type: 'area', description: 'Area on Faizabad Road', propertyTypes: ['2BHK', '3BHK', 'Shop'], nearbyLandmarks: ['Faizabad Road'], popular: false },
  { id: 'dayal-enclave', name: 'Dayal Enclave', slug: 'dayal-enclave', type: 'area', description: 'Residential enclave', propertyTypes: ['2BHK', '3BHK'], nearbyLandmarks: ['Indira Nagar'], popular: false },
  { id: 'cdri-mohalla', name: 'CDRI Mohalla', slug: 'cdri-mohalla', type: 'area', description: 'Area near CDRI', propertyTypes: ['2BHK', '3BHK', 'PG'], nearbyLandmarks: ['CDRI'], popular: false },
  { id: 'kathauta-chauraha-area', name: 'Kathauta Chauraha Area', slug: 'kathauta-chauraha-area', type: 'area', description: 'Junction area', propertyTypes: ['2BHK', '3BHK'], nearbyLandmarks: ['Gomti Nagar Extension'], popular: false },
  { id: 'air-force-station-mohalla', name: 'Air Force Station Mohalla', slug: 'air-force-station-mohalla', type: 'area', description: 'Area near Air Force Station', propertyTypes: ['2BHK', '3BHK'], nearbyLandmarks: ['Gomti Nagar'], popular: false },
  { id: 'hanuman-setu-mohalla', name: 'Hanuman Setu Mohalla', slug: 'hanuman-setu-mohalla', type: 'area', description: 'Area near Hanuman Setu', propertyTypes: ['2BHK', '3BHK'], nearbyLandmarks: ['Gomti Nagar'], popular: false },
  { id: 'vivek-khand', name: 'Vivek Khand', slug: 'vivek-khand', type: 'area', description: 'Sector in Gomti Nagar', propertyTypes: ['2BHK', '3BHK'], nearbyLandmarks: ['Gomti Nagar'], popular: false },
  { id: 'vishesh-khand', name: 'Vishesh Khand', slug: 'vishesh-khand', type: 'area', description: 'Sector in Gomti Nagar', propertyTypes: ['2BHK', '3BHK'], nearbyLandmarks: ['Gomti Nagar'], popular: false },
  { id: 'vastu-khand', name: 'Vastu Khand', slug: 'vastu-khand', type: 'area', description: 'Sector in Gomti Nagar', propertyTypes: ['2BHK', '3BHK'], nearbyLandmarks: ['Gomti Nagar'], popular: false },
]

// North Lucknow Mohallas (Aliganj, Jankipuram)
export const northMohallas: LucknowLocation[] = [
  { id: 'khurram-nagar-mohalla', name: 'Khurram Nagar', slug: 'khurram-nagar-mohalla', type: 'area', description: 'Residential area', propertyTypes: ['2BHK', '3BHK'], nearbyLandmarks: ['Faizabad Road'], popular: false },
  { id: 'kalyanpur-mohalla', name: 'Kalyanpur', slug: 'kalyanpur-mohalla', type: 'area', description: 'Residential area', propertyTypes: ['2BHK', '3BHK', 'Plot'], nearbyLandmarks: ['Kanpur Road'], popular: false },
  { id: 'bhitauli-mohalla', name: 'Bhitauli', slug: 'bhitauli-mohalla', type: 'area', description: 'Suburban area', propertyTypes: ['Plot', '2BHK'], nearbyLandmarks: ['Sitapur Road'], popular: false },
  { id: 'rahim-nagar', name: 'Rahim Nagar', slug: 'rahim-nagar', type: 'area', description: 'Residential area', propertyTypes: ['2BHK', '3BHK'], nearbyLandmarks: ['Aliganj'], popular: false },
  { id: 'chandganj-mohalla', name: 'Chandganj', slug: 'chandganj-mohalla', type: 'area', description: 'Residential area', propertyTypes: ['2BHK', '3BHK'], nearbyLandmarks: ['Aliganj'], popular: false },
  { id: 'faizullahganj', name: 'Faizullahganj', slug: 'faizullahganj', type: 'area', description: 'Traditional area', propertyTypes: ['1BHK', '2BHK'], nearbyLandmarks: ['Aliganj'], popular: false },
  { id: 'mahanagar-mohalla', name: 'Mahanagar Mohalla', slug: 'mahanagar-mohalla', type: 'area', description: 'Central area', propertyTypes: ['2BHK', '3BHK'], nearbyLandmarks: ['Mahanagar'], popular: false },
  { id: 'paper-mill-colony-mohalla', name: 'Paper Mill Colony Mohalla', slug: 'paper-mill-colony-mohalla', type: 'area', description: 'Residential area', propertyTypes: ['2BHK', '3BHK'], nearbyLandmarks: ['Nishatganj'], popular: false },
  { id: 'chandralok-mohalla', name: 'Chandralok', slug: 'chandralok-mohalla', type: 'area', description: 'Residential area', propertyTypes: ['2BHK', '3BHK'], nearbyLandmarks: ['Aliganj'], popular: false },
  { id: 'aliganj-a-block', name: 'Aliganj A Block', slug: 'aliganj-a-block', type: 'area', description: 'Block A in Aliganj', propertyTypes: ['2BHK', '3BHK'], nearbyLandmarks: ['Aliganj'], popular: false },
  { id: 'aliganj-b-block', name: 'Aliganj B Block', slug: 'aliganj-b-block', type: 'area', description: 'Block B in Aliganj', propertyTypes: ['2BHK', '3BHK'], nearbyLandmarks: ['Aliganj'], popular: false },
  { id: 'aliganj-g-block', name: 'Aliganj G Block', slug: 'aliganj-g-block', type: 'area', description: 'Block G in Aliganj', propertyTypes: ['2BHK', '3BHK'], nearbyLandmarks: ['Aliganj'], popular: false },
  { id: 'aliganj-h-block', name: 'Aliganj H Block', slug: 'aliganj-h-block', type: 'area', description: 'Block H in Aliganj', propertyTypes: ['2BHK', '3BHK', 'Villa'], nearbyLandmarks: ['Aliganj'], popular: true },
  { id: 'jankipuram-a-block', name: 'Jankipuram A Block', slug: 'jankipuram-a-block', type: 'area', description: 'Block A in Jankipuram', propertyTypes: ['2BHK', '3BHK'], nearbyLandmarks: ['Jankipuram'], popular: false },
  { id: 'jankipuram-b-block', name: 'Jankipuram B Block', slug: 'jankipuram-b-block', type: 'area', description: 'Block B in Jankipuram', propertyTypes: ['2BHK', '3BHK'], nearbyLandmarks: ['Jankipuram'], popular: false },
  { id: 'jankipuram-c-block', name: 'Jankipuram C Block', slug: 'jankipuram-c-block', type: 'area', description: 'Block C in Jankipuram', propertyTypes: ['2BHK', '3BHK'], nearbyLandmarks: ['Jankipuram'], popular: false },
  { id: 'jankipuram-d-block', name: 'Jankipuram D Block', slug: 'jankipuram-d-block', type: 'area', description: 'Block D in Jankipuram', propertyTypes: ['2BHK', '3BHK'], nearbyLandmarks: ['Jankipuram'], popular: false },
  { id: 'jankipuram-extension-mohalla', name: 'Jankipuram Extension', slug: 'jankipuram-extension-mohalla', type: 'area', description: 'Extension of Jankipuram', propertyTypes: ['2BHK', '3BHK', 'Plot'], nearbyLandmarks: ['Jankipuram'], popular: false },
  { id: 'kapoorthala-market-area', name: 'Kapoorthala Market Area', slug: 'kapoorthala-market-area', type: 'area', description: 'Market area in Kapoorthala', propertyTypes: ['Shop', '2BHK'], nearbyLandmarks: ['Kapoorthala'], popular: false },
  { id: 'kursi-road-mohalla', name: 'Kursi Road Mohalla', slug: 'kursi-road-mohalla', type: 'area', description: 'Area on Kursi Road', propertyTypes: ['2BHK', '3BHK', 'Plot'], nearbyLandmarks: ['Kursi Road'], popular: false },
  { id: 'madiyaon-mohalla', name: 'Madiyaon', slug: 'madiyaon-mohalla', type: 'area', description: 'Suburban area', propertyTypes: ['Plot', '2BHK'], nearbyLandmarks: ['Kursi Road'], popular: false },
  { id: 'triveni-nagar', name: 'Triveni Nagar', slug: 'triveni-nagar', type: 'area', description: 'Residential area', propertyTypes: ['2BHK', '3BHK'], nearbyLandmarks: ['Aliganj'], popular: false },
  { id: 'sugamau-mohalla', name: 'Sugamau Mohalla', slug: 'sugamau-mohalla', type: 'area', description: 'Suburban area', propertyTypes: ['Plot', '2BHK'], nearbyLandmarks: ['Jankipuram'], popular: false },
  { id: 'iim-road-mohalla', name: 'IIM Road Mohalla', slug: 'iim-road-mohalla', type: 'area', description: 'Area near IIM', propertyTypes: ['2BHK', '3BHK', 'PG'], nearbyLandmarks: ['IIM Lucknow'], popular: false },
  { id: 'badshah-nagar', name: 'Badshah Nagar', slug: 'badshah-nagar', type: 'area', description: 'Residential area', propertyTypes: ['2BHK', '3BHK'], nearbyLandmarks: ['Faizabad Road'], popular: false },
]

// South Lucknow Mohallas (Ashiyana, Raebareli Road, SGPGI)
export const southMohallas: LucknowLocation[] = [
  { id: 'ashiyana-colony-sector-a', name: 'Ashiyana Colony Sector A', slug: 'ashiyana-colony-sector-a', type: 'area', description: 'Sector A in Ashiyana', propertyTypes: ['2BHK', '3BHK', 'Villa'], nearbyLandmarks: ['Ashiyana'], popular: false },
  { id: 'ashiyana-colony-sector-b', name: 'Ashiyana Colony Sector B', slug: 'ashiyana-colony-sector-b', type: 'area', description: 'Sector B in Ashiyana', propertyTypes: ['2BHK', '3BHK'], nearbyLandmarks: ['Ashiyana'], popular: false },
  { id: 'ashiyana-colony-sector-c', name: 'Ashiyana Colony Sector C', slug: 'ashiyana-colony-sector-c', type: 'area', description: 'Sector C in Ashiyana', propertyTypes: ['2BHK', '3BHK'], nearbyLandmarks: ['Ashiyana'], popular: false },
  { id: 'ashiyana-colony-sector-d', name: 'Ashiyana Colony Sector D', slug: 'ashiyana-colony-sector-d', type: 'area', description: 'Sector D in Ashiyana', propertyTypes: ['2BHK', '3BHK'], nearbyLandmarks: ['Ashiyana'], popular: false },
  { id: 'alambagh-mohalla', name: 'Alambagh Mohalla', slug: 'alambagh-mohalla', type: 'area', description: 'Commercial area', propertyTypes: ['Shop', '2BHK'], nearbyLandmarks: ['Alambagh'], popular: false },
  { id: 'kanpur-road-mohalla', name: 'Kanpur Road Mohalla', slug: 'kanpur-road-mohalla', type: 'area', description: 'Area on Kanpur Road', propertyTypes: ['Shop', '2BHK', 'Commercial'], nearbyLandmarks: ['Kanpur Road'], popular: false },
  { id: 'transport-nagar-mohalla', name: 'Transport Nagar Mohalla', slug: 'transport-nagar-mohalla', type: 'area', description: 'Commercial area', propertyTypes: ['Shop', 'Warehouse', 'Commercial'], nearbyLandmarks: ['Transport Nagar'], popular: false },
  { id: 'telibagh-mohalla', name: 'Telibagh Mohalla', slug: 'telibagh-mohalla', type: 'area', description: 'Residential area', propertyTypes: ['2BHK', '3BHK', 'Plot'], nearbyLandmarks: ['Telibagh'], popular: false },
  { id: 'sgpgi-mohalla', name: 'SGPGI Mohalla', slug: 'sgpgi-mohalla', type: 'area', description: 'Area near SGPGI Hospital', propertyTypes: ['2BHK', '3BHK', 'PG'], nearbyLandmarks: ['SGPGI'], popular: true },
  { id: 'eldeco-udyan', name: 'Eldeco Udyan', slug: 'eldeco-udyan', type: 'area', description: 'Eldeco township', propertyTypes: ['2BHK', '3BHK', 'Villa'], nearbyLandmarks: ['Raebareli Road'], popular: false },
  { id: 'eldeco-ii', name: 'Eldeco II', slug: 'eldeco-ii', type: 'area', description: 'Eldeco Phase 2', propertyTypes: ['2BHK', '3BHK'], nearbyLandmarks: ['Raebareli Road'], popular: false },
  { id: 'bijnor-road-mohalla', name: 'Bijnor Road Mohalla', slug: 'bijnor-road-mohalla', type: 'area', description: 'Area on Bijnor Road', propertyTypes: ['2BHK', '3BHK'], nearbyLandmarks: ['Bijnor Road'], popular: false },
  { id: 'vrindavan-yojna-sector-1', name: 'Vrindavan Yojna Sector 1', slug: 'vrindavan-yojna-sector-1', type: 'area', description: 'Sector 1 in Vrindavan Yojna', propertyTypes: ['2BHK', '3BHK', 'Plot'], nearbyLandmarks: ['Raebareli Road'], popular: false },
  { id: 'vrindavan-yojna-sector-2', name: 'Vrindavan Yojna Sector 2', slug: 'vrindavan-yojna-sector-2', type: 'area', description: 'Sector 2 in Vrindavan Yojna', propertyTypes: ['2BHK', '3BHK'], nearbyLandmarks: ['Raebareli Road'], popular: false },
  { id: 'vrindavan-yojna-sector-3', name: 'Vrindavan Yojna Sector 3', slug: 'vrindavan-yojna-sector-3', type: 'area', description: 'Sector 3 in Vrindavan Yojna', propertyTypes: ['2BHK', '3BHK'], nearbyLandmarks: ['Raebareli Road'], popular: false },
  { id: 'krishna-nagar-mohalla', name: 'Krishna Nagar Mohalla', slug: 'krishna-nagar-mohalla', type: 'area', description: 'Residential area', propertyTypes: ['2BHK', '3BHK'], nearbyLandmarks: ['Kanpur Road'], popular: false },
  { id: 'rajni-khand', name: 'Rajni Khand', slug: 'rajni-khand', type: 'area', description: 'Sector in South City', propertyTypes: ['2BHK', '3BHK'], nearbyLandmarks: ['South City'], popular: false },
  { id: 'ratan-khand', name: 'Ratan Khand', slug: 'ratan-khand', type: 'area', description: 'Sector in South City', propertyTypes: ['2BHK', '3BHK'], nearbyLandmarks: ['South City'], popular: false },
  { id: 'radhey-khand', name: 'Radhey Khand', slug: 'radhey-khand', type: 'area', description: 'Sector in South City', propertyTypes: ['2BHK', '3BHK'], nearbyLandmarks: ['South City'], popular: false },
  { id: 'sharda-nagar', name: 'Sharda Nagar', slug: 'sharda-nagar', type: 'area', description: 'Residential area', propertyTypes: ['2BHK', '3BHK'], nearbyLandmarks: ['Kanpur Road'], popular: false },
  { id: 'sarojini-nagar-mohalla', name: 'Sarojini Nagar', slug: 'sarojini-nagar-mohalla', type: 'area', description: 'Residential area', propertyTypes: ['2BHK', '3BHK'], nearbyLandmarks: ['Kanpur Road'], popular: false },
  { id: 'banthra-mohalla', name: 'Banthra Mohalla', slug: 'banthra-mohalla', type: 'area', description: 'Suburban area', propertyTypes: ['Plot', '2BHK'], nearbyLandmarks: ['Banthra'], popular: false },
  { id: 'omaxe-city-sector-a', name: 'Omaxe City Sector A', slug: 'omaxe-city-sector-a', type: 'area', description: 'Sector A in Omaxe City', propertyTypes: ['2BHK', '3BHK', 'Villa'], nearbyLandmarks: ['Raebareli Road'], popular: false },
  { id: 'omaxe-city-sector-b', name: 'Omaxe City Sector B', slug: 'omaxe-city-sector-b', type: 'area', description: 'Sector B in Omaxe City', propertyTypes: ['2BHK', '3BHK'], nearbyLandmarks: ['Raebareli Road'], popular: false },
  { id: 'ansal-api-sector-a', name: 'Ansal API Sector A', slug: 'ansal-api-sector-a', type: 'area', description: 'Sector A in Ansal API', propertyTypes: ['2BHK', '3BHK', 'Villa'], nearbyLandmarks: ['Ansal API'], popular: false },
  { id: 'ansal-api-sector-b', name: 'Ansal API Sector B', slug: 'ansal-api-sector-b', type: 'area', description: 'Sector B in Ansal API', propertyTypes: ['2BHK', '3BHK'], nearbyLandmarks: ['Ansal API'], popular: false },
  { id: 'ahmamau', name: 'Ahmamau', slug: 'ahmamau', type: 'area', description: 'Developing area', propertyTypes: ['Plot', '2BHK'], nearbyLandmarks: ['Raebareli Road'], popular: false },
  { id: 'utrathia', name: 'Utrathia', slug: 'utrathia', type: 'area', description: 'Suburban area', propertyTypes: ['Plot', '2BHK'], nearbyLandmarks: ['Raebareli Road'], popular: false },
  { id: 'vrindavan-colony-mohalla', name: 'Vrindavan Colony', slug: 'vrindavan-colony-mohalla', type: 'area', description: 'Residential colony', propertyTypes: ['2BHK', '3BHK'], nearbyLandmarks: ['Aliganj'], popular: false },
  { id: 'raebareli-road-sectors', name: 'Raebareli Road Sectors', slug: 'raebareli-road-sectors', type: 'area', description: 'Sectors on Raebareli Road', propertyTypes: ['2BHK', '3BHK', 'Plot'], nearbyLandmarks: ['Raebareli Road'], popular: false },
  { id: 'telibagh-green-valley', name: 'Telibagh Green Valley', slug: 'telibagh-green-valley', type: 'area', description: 'Green Valley in Telibagh', propertyTypes: ['2BHK', '3BHK', 'Villa'], nearbyLandmarks: ['Telibagh'], popular: false },
  { id: 'alambagh-chowraha-area', name: 'Alambagh Chowraha Area', slug: 'alambagh-chowraha-area', type: 'area', description: 'Junction area in Alambagh', propertyTypes: ['Shop', '2BHK'], nearbyLandmarks: ['Alambagh'], popular: false },
]

// West Lucknow Mohallas (Kalyanpur, Rajajipuram, Aishbagh)
export const westMohallas: LucknowLocation[] = [
  { id: 'rajajipuram-a-block-mohalla', name: 'Rajajipuram A Block', slug: 'rajajipuram-a-block-mohalla', type: 'area', description: 'Block A in Rajajipuram', propertyTypes: ['2BHK', '3BHK'], nearbyLandmarks: ['Rajajipuram'], popular: false },
  { id: 'rajajipuram-b-block-mohalla', name: 'Rajajipuram B Block', slug: 'rajajipuram-b-block-mohalla', type: 'area', description: 'Block B in Rajajipuram', propertyTypes: ['2BHK', '3BHK'], nearbyLandmarks: ['Rajajipuram'], popular: false },
  { id: 'rajajipuram-c-block-mohalla', name: 'Rajajipuram C Block', slug: 'rajajipuram-c-block-mohalla', type: 'area', description: 'Block C in Rajajipuram', propertyTypes: ['2BHK', '3BHK'], nearbyLandmarks: ['Rajajipuram'], popular: false },
  { id: 'rajajipuram-d-block-mohalla', name: 'Rajajipuram D Block', slug: 'rajajipuram-d-block-mohalla', type: 'area', description: 'Block D in Rajajipuram', propertyTypes: ['2BHK', '3BHK'], nearbyLandmarks: ['Rajajipuram'], popular: false },
  { id: 'aishbagh-mohalla', name: 'Aishbagh Mohalla', slug: 'aishbagh-mohalla', type: 'area', description: 'Traditional area', propertyTypes: ['1BHK', '2BHK', 'Shop'], nearbyLandmarks: ['Aishbagh'], popular: false },
  { id: 'talkatora-mohalla', name: 'Talkatora Mohalla', slug: 'talkatora-mohalla', type: 'area', description: 'Residential area', propertyTypes: ['2BHK', '3BHK'], nearbyLandmarks: ['Mahanagar'], popular: false },
  { id: 'dubagga-mohalla', name: 'Dubagga', slug: 'dubagga-mohalla', type: 'area', description: 'Developing area', propertyTypes: ['Plot', '2BHK'], nearbyLandmarks: ['Sitapur Road'], popular: false },
  { id: 'buddeshwar', name: 'Buddeshwar', slug: 'buddeshwar', type: 'area', description: 'Traditional area', propertyTypes: ['1BHK', '2BHK'], nearbyLandmarks: ['Chowk'], popular: false },
  { id: 'jail-road-mohalla', name: 'Jail Road Mohalla', slug: 'jail-road-mohalla', type: 'area', description: 'Area on Jail Road', propertyTypes: ['2BHK', 'Shop'], nearbyLandmarks: ['Hazratganj'], popular: false },
  { id: 'alamnagar-mohalla', name: 'Alamnagar Mohalla', slug: 'alamnagar-mohalla', type: 'area', description: 'Residential area', propertyTypes: ['2BHK', '3BHK'], nearbyLandmarks: ['Alambagh'], popular: false },
  { id: 'para-mohalla', name: 'Para Mohalla', slug: 'para-mohalla', type: 'area', description: 'Traditional mohalla', propertyTypes: ['1BHK', '2BHK'], nearbyLandmarks: ['Chowk'], popular: false },
  { id: 'sarfarazganj', name: 'Sarfarazganj', slug: 'sarfarazganj', type: 'area', description: 'Traditional area', propertyTypes: ['1BHK', '2BHK', 'Shop'], nearbyLandmarks: ['Chowk'], popular: false },
  { id: 'qila-mohalla', name: 'Qila Mohalla', slug: 'qila-mohalla', type: 'area', description: 'Historic area', propertyTypes: ['1BHK', 'Shop'], nearbyLandmarks: ['Chowk'], popular: false },
  { id: 'thakurganj-mohalla', name: 'Thakurganj', slug: 'thakurganj-mohalla', type: 'area', description: 'Traditional area', propertyTypes: ['1BHK', '2BHK'], nearbyLandmarks: ['Chowk'], popular: false },
  { id: 'daulatganj-mohalla', name: 'Daulatganj Mohalla', slug: 'daulatganj-mohalla', type: 'area', description: 'Traditional area', propertyTypes: ['1BHK', '2BHK', 'Shop'], nearbyLandmarks: ['Chowk'], popular: false },
  { id: 'mawaiya-mohalla', name: 'Mawaiya Mohalla', slug: 'mawaiya-mohalla', type: 'area', description: 'Residential area', propertyTypes: ['2BHK', '3BHK'], nearbyLandmarks: ['Alambagh'], popular: false },
  { id: 'golaganj-mohalla', name: 'Golaganj Mohalla', slug: 'golaganj-mohalla', type: 'area', description: 'Commercial area', propertyTypes: ['Shop', '2BHK'], nearbyLandmarks: ['Hazratganj'], popular: false },
  { id: 'bada-imambara-mohalla', name: 'Bada Imambara Mohalla', slug: 'bada-imambara-mohalla', type: 'area', description: 'Historic area', propertyTypes: ['Shop', '1BHK'], nearbyLandmarks: ['Bada Imambara'], popular: false },
  { id: 'nakhas-mohalla', name: 'Nakhas Mohalla', slug: 'nakhas-mohalla', type: 'area', description: 'Traditional market area', propertyTypes: ['Shop', '1BHK'], nearbyLandmarks: ['Chowk'], popular: false },
  { id: 'nakkhas-ganj', name: 'Nakkhas Ganj', slug: 'nakkhas-ganj', type: 'area', description: 'Market area', propertyTypes: ['Shop', '1BHK'], nearbyLandmarks: ['Chowk'], popular: false },
  { id: 'hata-mohalla', name: 'Hata Mohalla', slug: 'hata-mohalla', type: 'area', description: 'Traditional mohalla', propertyTypes: ['1BHK', '2BHK'], nearbyLandmarks: ['Chowk'], popular: false },
  { id: 'husainabad-mohalla', name: 'Husainabad Mohalla', slug: 'husainabad-mohalla', type: 'area', description: 'Historic area', propertyTypes: ['1BHK', 'Shop'], nearbyLandmarks: ['Husainabad'], popular: false },
  { id: 'victoria-street', name: 'Victoria Street', slug: 'victoria-street', type: 'area', description: 'Central area', propertyTypes: ['Shop', '2BHK'], nearbyLandmarks: ['Hazratganj'], popular: false },
  { id: 'chowk-bazaar-mohalla', name: 'Chowk Bazaar Mohalla', slug: 'chowk-bazaar-mohalla', type: 'area', description: 'Market area', propertyTypes: ['Shop', 'Commercial'], nearbyLandmarks: ['Chowk'], popular: false },
  { id: 'saadatganj-mohalla', name: 'Saadatganj Mohalla', slug: 'saadatganj-mohalla', type: 'area', description: 'Traditional area', propertyTypes: ['1BHK', '2BHK'], nearbyLandmarks: ['Chowk'], popular: false },
  { id: 'sarai-mali-khan', name: 'Sarai Mali Khan', slug: 'sarai-mali-khan', type: 'area', description: 'Traditional area', propertyTypes: ['1BHK', '2BHK'], nearbyLandmarks: ['Chowk'], popular: false },
  { id: 'rakabganj-mohalla', name: 'Rakabganj Mohalla', slug: 'rakabganj-mohalla', type: 'area', description: 'Traditional area', propertyTypes: ['1BHK', '2BHK', 'Shop'], nearbyLandmarks: ['Hazratganj'], popular: false },
  { id: 'aishbagh-industrial-area', name: 'Aishbagh Industrial Area', slug: 'aishbagh-industrial-area', type: 'area', description: 'Industrial area', propertyTypes: ['Warehouse', 'Commercial'], nearbyLandmarks: ['Aishbagh'], popular: false },
  { id: 'mohanlalganj-town', name: 'Mohanlalganj Town', slug: 'mohanlalganj-town', type: 'area', description: 'Suburban town', propertyTypes: ['Plot', '2BHK'], nearbyLandmarks: ['Mohanlalganj'], popular: false },
  { id: 'gosainganj', name: 'Gosainganj', slug: 'gosainganj', type: 'area', description: 'Suburban area', propertyTypes: ['Plot', '2BHK'], nearbyLandmarks: ['Kanpur Road'], popular: false },
  { id: 'kakori-mohalla', name: 'Kakori Mohalla', slug: 'kakori-mohalla', type: 'area', description: 'Historic area', propertyTypes: ['Plot', '2BHK'], nearbyLandmarks: ['Kakori'], popular: false },
  { id: 'banthara', name: 'Banthara', slug: 'banthara', type: 'area', description: 'Suburban area', propertyTypes: ['Plot', '2BHK'], nearbyLandmarks: ['Kanpur Road'], popular: false },
  { id: 'manak-nagar', name: 'Manak Nagar', slug: 'manak-nagar', type: 'area', description: 'Residential area', propertyTypes: ['2BHK', '3BHK'], nearbyLandmarks: ['Alambagh'], popular: false },
  { id: 'charbagh-katra', name: 'Charbagh Katra', slug: 'charbagh-katra', type: 'area', description: 'Area near Charbagh', propertyTypes: ['Shop', '1BHK', 'PG'], nearbyLandmarks: ['Charbagh'], popular: false },
  { id: 'alamnagar-railway-colony', name: 'Alamnagar Railway Colony', slug: 'alamnagar-railway-colony', type: 'area', description: 'Railway colony', propertyTypes: ['2BHK', '3BHK'], nearbyLandmarks: ['Alambagh'], popular: false },
]

// Export all mohallas
export const allMohallas = [...centralMohallas, ...eastMohallas, ...northMohallas, ...southMohallas, ...westMohallas]
