/**
 * Notification Sender Service for Estato
 * Sends push notifications via Firebase Cloud Messaging (FCM)
 */

const admin = require('firebase-admin');
const { generateSmartNotification } = require('./notification-ai');
const { logNotification } = require('./notification-rules');

// Initialize Firebase Admin (if not already initialized)
let firebaseInitialized = false;

function initializeFirebase() {
  if (firebaseInitialized) return;

  try {
    // Check if Firebase is already initialized
    if (admin.apps.length === 0) {
      // Option 1: Using service account file
      if (process.env.FIREBASE_SERVICE_ACCOUNT_PATH) {
        const serviceAccount = require(process.env.FIREBASE_SERVICE_ACCOUNT_PATH);
        admin.initializeApp({
          credential: admin.credential.cert(serviceAccount)
        });
      }
      // Option 2: Using environment variables
      else if (process.env.FIREBASE_PROJECT_ID) {
        admin.initializeApp({
          credential: admin.credential.cert({
            projectId: process.env.FIREBASE_PROJECT_ID,
            clientEmail: process.env.FIREBASE_CLIENT_EMAIL,
            privateKey: process.env.FIREBASE_PRIVATE_KEY?.replace(/\\n/g, '\n')
          })
        });
      }
      // Option 3: Default credentials (for deployed environments)
      else {
        admin.initializeApp();
      }
    }
    
    firebaseInitialized = true;
    console.log('✅ Firebase Admin initialized successfully');
  } catch (error) {
    console.error('❌ Firebase initialization error:', error.message);
    console.warn('⚠️ Notifications will run in simulation mode');
  }
}

/**
 * Send notification to single user
 */
async function sendNotificationToUser(userId, eventData, fcmToken) {
  try {
    // Generate AI notification text
    const aiResult = await generateSmartNotification(eventData);
    
    if (!aiResult.success) {
      console.error('Failed to generate notification text');
      return { success: false, error: 'Failed to generate notification' };
    }

    const notificationText = aiResult.message;
    console.log(`📝 Generated notification: "${notificationText}"`);

    // Prepare notification payload
    const notification = {
      title: 'Estato Property',
      body: notificationText,
    };

    const data = {
      event: eventData.event,
      area: eventData.area || '',
      propertyId: eventData.propertyId || '',
      timestamp: Date.now().toString()
    };

    // Send via FCM
    if (firebaseInitialized && fcmToken) {
      try {
        const message = {
          notification,
          data,
          token: fcmToken,
          android: {
            priority: 'high',
            notification: {
              icon: 'ic_notification',
              color: '#2196F3',
              sound: 'default',
              channelId: 'estato_notifications'
            }
          },
          apns: {
            payload: {
              aps: {
                sound: 'default',
                badge: 1
              }
            }
          }
        };

        const response = await admin.messaging().send(message);
        console.log(`✅ Notification sent successfully: ${response}`);
        
        // Log notification
        logNotification(userId);

        return {
          success: true,
          messageId: response,
          notificationText,
          generatedBy: aiResult.generatedBy,
          model: aiResult.model
        };
      } catch (fcmError) {
        console.error('FCM send error:', fcmError);
        return {
          success: false,
          error: fcmError.message,
          notificationText
        };
      }
    } else {
      // Simulation mode (for testing without Firebase)
      console.log('📱 [SIMULATION] Notification would be sent:');
      console.log(`   User: ${userId}`);
      console.log(`   Title: ${notification.title}`);
      console.log(`   Body: ${notificationText}`);
      console.log(`   Generated by: ${aiResult.generatedBy}`);
      
      // Log notification even in simulation
      logNotification(userId);

      return {
        success: true,
        simulation: true,
        notificationText,
        generatedBy: aiResult.generatedBy,
        model: aiResult.model
      };
    }
  } catch (error) {
    console.error('Error sending notification:', error);
    return {
      success: false,
      error: error.message
    };
  }
}

/**
 * Send notifications to multiple users
 */
async function sendBulkNotifications(notifications) {
  const results = [];

  for (const notification of notifications) {
    const { userId, eventData, fcmToken } = notification;
    const result = await sendNotificationToUser(userId, eventData, fcmToken);
    results.push({
      userId,
      ...result
    });

    // Small delay to avoid rate limits
    await new Promise(resolve => setTimeout(resolve, 100));
  }

  return results;
}

/**
 * Send notification with topic (for broadcast)
 */
async function sendTopicNotification(topic, eventData) {
  try {
    // Generate AI notification text
    const aiResult = await generateSmartNotification(eventData);
    
    if (!aiResult.success) {
      return { success: false, error: 'Failed to generate notification' };
    }

    const notificationText = aiResult.message;

    if (firebaseInitialized) {
      const message = {
        notification: {
          title: 'Estato Property',
          body: notificationText
        },
        data: {
          event: eventData.event,
          timestamp: Date.now().toString()
        },
        topic: topic
      };

      const response = await admin.messaging().send(message);
      console.log(`✅ Topic notification sent: ${response}`);

      return {
        success: true,
        messageId: response,
        notificationText,
        generatedBy: aiResult.generatedBy
      };
    } else {
      console.log(`📱 [SIMULATION] Topic notification: ${topic}`);
      console.log(`   Body: ${notificationText}`);
      return {
        success: true,
        simulation: true,
        notificationText
      };
    }
  } catch (error) {
    console.error('Error sending topic notification:', error);
    return {
      success: false,
      error: error.message
    };
  }
}

/**
 * Test notification
 */
async function sendTestNotification(fcmToken) {
  const testEventData = {
    event: 'new_property',
    area: 'Gomti Nagar',
    bhk: '2BHK',
    budget: '15000',
    user_type: 'buyer',
    language: 'hinglish',
    tone: 'friendly'
  };

  return await sendNotificationToUser('test-user', testEventData, fcmToken);
}

// Initialize Firebase on module load
initializeFirebase();

module.exports = {
  sendNotificationToUser,
  sendBulkNotifications,
  sendTopicNotification,
  sendTestNotification,
  initializeFirebase
};

