import { Property } from './supabase/types'

// Mock properties data for demo - Reduced set covering all property types
export const mockProperties: Property[] = [
  {
    id: '1',
    title: 'Modern 3BHK Apartment in Gomti Nagar',
    description: 'Beautiful modern apartment with stunning city views. Fully furnished with premium amenities including gym, swimming pool, and 24/7 security.',
    type: 'flat',
    listing_type: 'rent',
    price: 35000,
    location: 'Gomti Nagar',
    city: 'Lucknow',
    area: 'Gomti Nagar',
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1200,
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
      'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800',
    ],
    amenities: ['parking', 'security', 'elevator', 'gym', 'pool', 'wifi'],
    latitude: 26.8467,
    longitude: 80.9462,
    owner_id: 'owner-1',
    owner_name: 'Rajesh Kumar',
    owner_email: 'rajesh@example.com',
    owner_phone: '+91 98765 43210',
    status: 'active',
    featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    title: 'Luxury 4BHK Villa in Indira Nagar',
    description: 'Spacious 4BHK villa with private garden and modern amenities. Located in a peaceful neighborhood with easy access to schools and shopping centers.',
    type: 'villa',
    listing_type: 'rent',
    price: 75000,
    location: 'Indira Nagar',
    city: 'Lucknow',
    area: 'Indira Nagar',
    bedrooms: 4,
    bathrooms: 3,
    sqft: 3500,
    images: [
      'https://images.unsplash.com/photo-1613977257363-707ba9348227?w=800',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800',
    ],
    amenities: ['parking', 'security', 'garden', 'wifi', 'pool'],
    latitude: 26.8985,
    longitude: 80.9888,
    owner_id: 'owner-2',
    owner_name: 'Priya Sharma',
    owner_email: 'priya@example.com',
    owner_phone: '+91 98765 43211',
    status: 'active',
    featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    title: 'Cozy 2BHK House for Rent in Alambagh',
    description: 'Well-maintained 2BHK house in a quiet residential area. Close to public transport and markets. Perfect for small families.',
    type: 'house',
    listing_type: 'rent',
    price: 18000,
    location: 'Alambagh',
    city: 'Lucknow',
    area: 'Alambagh',
    bedrooms: 2,
    bathrooms: 2,
    sqft: 900,
    images: [
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
    ],
    amenities: ['parking', 'security', 'wifi'],
    latitude: 26.7854,
    longitude: 80.9036,
    owner_id: 'owner-3',
    owner_name: 'Amit Patel',
    owner_email: 'amit@example.com',
    owner_phone: '+91 98765 43212',
    status: 'active',
    featured: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '4',
    title: '3BHK Flat for Sale in Hazratganj',
    description: 'Premium 3BHK apartment in the heart of Lucknow. Perfect location with all modern amenities. Ready to move in.',
    type: 'flat',
    listing_type: 'sale',
    price: 8500000,
    location: 'Hazratganj',
    city: 'Lucknow',
    area: 'Hazratganj',
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1350,
    images: [
      'https://images.unsplash.com/photo-1560185007-c5ca9d2c014d?w=800',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
    ],
    amenities: ['parking', 'security', 'elevator', 'gym', 'wifi'],
    latitude: 26.8508,
    longitude: 80.9467,
    owner_id: 'owner-4',
    owner_name: 'Sunita Verma',
    owner_email: 'sunita@example.com',
    owner_phone: '+91 98765 43213',
    status: 'active',
    featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '5',
    title: 'Independent Villa for Sale in Jankipuram',
    description: 'Beautiful independent villa with modern architecture. Spacious rooms, garden, and parking. Ideal for families looking for luxury living.',
    type: 'villa',
    listing_type: 'sale',
    price: 12500000,
    location: 'Jankipuram',
    city: 'Lucknow',
    area: 'Jankipuram',
    bedrooms: 5,
    bathrooms: 4,
    sqft: 4200,
    images: [
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800',
    ],
    amenities: ['parking', 'security', 'garden', 'wifi', 'pool', 'clubhouse'],
    latitude: 26.9200,
    longitude: 80.9500,
    owner_id: 'owner-5',
    owner_name: 'Vikram Singh',
    owner_email: 'vikram@example.com',
    owner_phone: '+91 98765 43214',
    status: 'active',
    featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '6',
    title: 'Commercial Shop for Rent in Kapoorthala',
    description: 'Prime location shop in Kapoorthala market. High footfall area with good visibility. Perfect for retail business or showroom.',
    type: 'shop',
    listing_type: 'rent',
    price: 45000,
    location: 'Kapoorthala',
    city: 'Lucknow',
    area: 'Kapoorthala',
    bedrooms: 0,
    bathrooms: 1,
    sqft: 700,
    images: [
      'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800',
      'https://images.unsplash.com/photo-1445205170230-053b83016050?w=800',
    ],
    amenities: ['parking', 'security'],
    latitude: 26.8567,
    longitude: 80.9414,
    owner_id: 'owner-6',
    owner_name: 'Commercial Spaces',
    owner_email: 'commercial@example.com',
    owner_phone: '+91 98765 43215',
    status: 'active',
    featured: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '7',
    title: 'Premium Office Space in Vibhuti Khand',
    description: 'Modern office space with all amenities. Close to IT parks. Perfect for startups and established businesses.',
    type: 'office',
    listing_type: 'rent',
    price: 85000,
    location: 'Vibhuti Khand',
    city: 'Lucknow',
    area: 'Gomti Nagar Extension',
    bedrooms: 0,
    bathrooms: 2,
    sqft: 2000,
    images: [
      'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800',
      'https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=800',
    ],
    amenities: ['parking', 'security', 'elevator', 'wifi', 'ac'],
    latitude: 26.8700,
    longitude: 80.9600,
    owner_id: 'owner-7',
    owner_name: 'Elite Builders',
    owner_email: 'elite@example.com',
    owner_phone: '+91 98765 43216',
    status: 'active',
    featured: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '8',
    title: 'Residential Plot in Sultanpur Road',
    description: 'Prime residential plot in developing area. Clear title, ready for construction. Good investment opportunity.',
    type: 'plot',
    listing_type: 'sale',
    price: 4500000,
    location: 'Sultanpur Road',
    city: 'Lucknow',
    area: 'Sultanpur Road',
    bedrooms: 0,
    bathrooms: 0,
    sqft: 2400,
    images: [
      'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800',
    ],
    amenities: [],
    latitude: 26.7800,
    longitude: 81.0200,
    owner_id: 'owner-8',
    owner_name: 'Land Developers',
    owner_email: 'land@example.com',
    owner_phone: '+91 98765 43217',
    status: 'active',
    featured: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '9',
    title: 'Affordable 1BHK Flat for Rent in Aliganj',
    description: 'Compact 1BHK flat ideal for bachelors or young couples. Well-connected area with all basic amenities nearby.',
    type: 'flat',
    listing_type: 'rent',
    price: 12000,
    location: 'Aliganj',
    city: 'Lucknow',
    area: 'Aliganj',
    bedrooms: 1,
    bathrooms: 1,
    sqft: 550,
    images: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
    ],
    amenities: ['parking', 'wifi'],
    latitude: 26.8900,
    longitude: 80.9300,
    owner_id: 'owner-9',
    owner_name: 'Aliganj Rentals',
    owner_email: 'aliganj@example.com',
    owner_phone: '+91 98765 43218',
    status: 'active',
    featured: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '10',
    title: 'Duplex House for Sale in Mahanagar',
    description: 'Stunning duplex house with modern design. Spacious living areas, modular kitchen, and beautiful terrace garden.',
    type: 'house',
    listing_type: 'sale',
    price: 9800000,
    location: 'Mahanagar',
    city: 'Lucknow',
    area: 'Mahanagar',
    bedrooms: 4,
    bathrooms: 3,
    sqft: 2800,
    images: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800',
    ],
    amenities: ['parking', 'security', 'garden', 'wifi'],
    latitude: 26.8650,
    longitude: 80.9350,
    owner_id: 'owner-10',
    owner_name: 'Mahanagar Properties',
    owner_email: 'mahanagar@example.com',
    owner_phone: '+91 98765 43219',
    status: 'active',
    featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

// Mock user data
export const mockUsers = [
  {
    id: 'user-1',
    email: 'demo@example.com',
    full_name: 'Demo User',
    phone: '+91 98765 43210',
    role: 'user' as const,
    avatar_url: null,
    created_at: new Date().toISOString(),
  },
  {
    id: 'admin-1',
    email: 'admin@example.com',
    full_name: 'Admin User',
    phone: '+91 98765 43200',
    role: 'admin' as const,
    avatar_url: null,
    created_at: new Date().toISOString(),
  },
]

// Check if Supabase is configured
export const isSupabaseConfigured = () => {
  return !!(
    process.env.NEXT_PUBLIC_SUPABASE_URL &&
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY &&
    process.env.NEXT_PUBLIC_SUPABASE_URL !== 'your_supabase_project_url'
  )
}
