import { Property } from './supabase/types'

// Mock properties data for demo - All properties in Lucknow
export const mockProperties: Property[] = [
  {
    id: '1',
    title: 'Modern 3BHK Apartment in Gomti Nagar',
    description: 'Beautiful modern apartment with stunning city views. Fully furnished with premium amenities including gym, swimming pool, and 24/7 security. Perfect for families looking for a luxurious lifestyle in the heart of Lucknow.',
    type: 'flat',
    listing_type: 'rent',
    price: 35000,
    location: 'Gomti Nagar',
    city: 'Lucknow',
    area: 'Gomti Nagar',
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1200,
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
      'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
    ],
    amenities: ['parking', 'security', 'elevator', 'gym', 'pool', 'wifi'],
    latitude: 26.8467,
    longitude: 80.9462,
    owner_id: 'owner-1',
    owner_name: 'Rajesh Kumar',
    owner_email: 'rajesh@example.com',
    owner_phone: '+91 98765 43210',
    status: 'active',
    featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    title: 'Luxury 4BHK Villa in Indira Nagar',
    description: 'Spacious 4BHK villa with private garden and modern amenities. Located in a peaceful neighborhood with easy access to schools and shopping centers. Perfect for large families.',
    type: 'villa',
    listing_type: 'rent',
    price: 75000,
    location: 'Indira Nagar',
    city: 'Lucknow',
    area: 'Indira Nagar',
    bedrooms: 4,
    bathrooms: 3,
    sqft: 3500,
    images: [
      'https://images.unsplash.com/photo-1613977257363-707ba9348227?w=800',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800',
      'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800',
    ],
    amenities: ['parking', 'security', 'garden', 'wifi', 'pool'],
    latitude: 26.8985,
    longitude: 80.9888,
    owner_id: 'owner-2',
    owner_name: 'Priya Sharma',
    owner_email: 'priya@example.com',
    owner_phone: '+91 98765 43211',
    status: 'active',
    featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    title: 'Cozy 2BHK House for Rent in Alambagh',
    description: 'Well-maintained 2BHK house in a quiet residential area. Close to public transport and markets. Perfect for small families or working professionals. Available for immediate possession.',
    type: 'house',
    listing_type: 'rent',
    price: 18000,
    location: 'Alambagh',
    city: 'Lucknow',
    area: 'Alambagh',
    bedrooms: 2,
    bathrooms: 2,
    sqft: 900,
    images: [
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
    ],
    amenities: ['parking', 'security', 'wifi'],
    latitude: 26.7854,
    longitude: 80.9036,
    owner_id: 'owner-3',
    owner_name: 'Amit Patel',
    owner_email: 'amit@example.com',
    owner_phone: '+91 98765 43212',
    status: 'active',
    featured: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '4',
    title: '3BHK Flat for Sale in Hazratganj',
    description: 'Premium 3BHK apartment in the heart of Lucknow. Perfect location with all modern amenities. Ideal for families. Ready to move in.',
    type: 'flat',
    listing_type: 'sale',
    price: 8500000,
    location: 'Hazratganj',
    city: 'Lucknow',
    area: 'Hazratganj',
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1400,
    images: [
      'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800',
      'https://images.unsplash.com/photo-1497366754035-f200968a6e72?w=800',
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
    ],
    amenities: ['parking', 'security', 'elevator', 'wifi', 'gym'],
    latitude: 26.8486,
    longitude: 80.9469,
    owner_id: 'owner-4',
    owner_name: 'Real Estate Solutions',
    owner_email: 'realestate@example.com',
    owner_phone: '+91 98765 43213',
    status: 'active',
    featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '5',
    title: '2BHK Apartment for Rent in Mahanagar',
    description: 'Semi-furnished 2BHK apartment in prime location. Close to schools, hospitals, and shopping malls. Good connectivity. Perfect for families.',
    type: 'flat',
    listing_type: 'rent',
    price: 22000,
    location: 'Mahanagar',
    city: 'Lucknow',
    area: 'Mahanagar',
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1000,
    images: [
      'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800',
      'https://images.unsplash.com/photo-1445205170230-053b83016050?w=800',
      'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800',
    ],
    amenities: ['parking', 'security', 'elevator', 'wifi'],
    latitude: 26.8500,
    longitude: 80.9300,
    owner_id: 'owner-5',
    owner_name: 'Property Consultants',
    owner_email: 'consultants@example.com',
    owner_phone: '+91 98765 43214',
    status: 'active',
    featured: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '6',
    title: 'Independent House for Sale in Nirala Nagar',
    description: 'Spacious 4BHK independent house with modern amenities. Large garden, parking space, and all facilities. Perfect for large families. Ready to move.',
    type: 'house',
    listing_type: 'sale',
    price: 12000000,
    location: 'Nirala Nagar',
    city: 'Lucknow',
    area: 'Nirala Nagar',
    bedrooms: 4,
    bathrooms: 3,
    sqft: 2800,
    images: [
      'https://images.unsplash.com/photo-1600585154084-4e5fe7c39198?w=800',
      'https://images.unsplash.com/photo-1600607687644-c7171b42498b?w=800',
      'https://images.unsplash.com/photo-1613977257363-707ba9348227?w=800',
    ],
    amenities: ['parking', 'security', 'garden', 'wifi'],
    latitude: 26.8625,
    longitude: 80.9500,
    owner_id: 'owner-6',
    owner_name: 'Home Builders',
    owner_email: 'builders@example.com',
    owner_phone: '+91 98765 43215',
    status: 'active',
    featured: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '7',
    title: '1BHK Flat for Rent in Aminabad',
    description: 'Furnished 1BHK flat in Aminabad market area. Close to all facilities. Perfect for students or working professionals. Available immediately.',
    type: 'flat',
    listing_type: 'rent',
    price: 12000,
    location: 'Aminabad',
    city: 'Lucknow',
    area: 'Aminabad',
    bedrooms: 1,
    bathrooms: 1,
    sqft: 550,
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
      'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800',
    ],
    amenities: ['parking', 'security', 'wifi'],
    latitude: 26.8381,
    longitude: 80.9236,
    owner_id: 'owner-7',
    owner_name: 'Aminabad Properties',
    owner_email: 'aminabad@example.com',
    owner_phone: '+91 98765 43216',
    status: 'active',
    featured: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '8',
    title: 'Commercial Shop for Rent in Kapoorthala',
    description: 'Prime location shop in Kapoorthala market. High footfall area with good visibility. Perfect for retail business, showroom, or office.',
    type: 'shop',
    listing_type: 'rent',
    price: 45000,
    location: 'Kapoorthala',
    city: 'Lucknow',
    area: 'Kapoorthala',
    bedrooms: 0,
    bathrooms: 1,
    sqft: 700,
    images: [
      'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800',
      'https://images.unsplash.com/photo-1445205170230-053b83016050?w=800',
    ],
    amenities: ['parking', 'security'],
    latitude: 26.8567,
    longitude: 80.9414,
    owner_id: 'owner-8',
    owner_name: 'Commercial Spaces',
    owner_email: 'commercial@example.com',
    owner_phone: '+91 98765 43217',
    status: 'active',
    featured: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '9',
    title: 'Premium 3BHK Apartment for Sale in Vibhuti Khand',
    description: 'Luxurious 3BHK apartment in premium location. Fully furnished with modern interiors. Close to IT parks and educational institutions. Perfect investment opportunity.',
    type: 'flat',
    listing_type: 'sale',
    price: 9500000,
    location: 'Vibhuti Khand',
    city: 'Lucknow',
    area: 'Gomti Nagar Extension',
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1450,
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
      'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
    ],
    amenities: ['parking', 'security', 'elevator', 'gym', 'pool', 'wifi', 'clubhouse'],
    latitude: 26.8700,
    longitude: 80.9600,
    owner_id: 'owner-9',
    owner_name: 'Elite Builders',
    owner_email: 'elite@example.com',
    owner_phone: '+91 98765 43218',
    status: 'active',
    featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '10',
    title: 'Spacious 2BHK Flat for Rent in Rajajipuram',
    description: 'Well-ventilated 2BHK flat in peaceful area. Semi-furnished with all basic amenities. Close to railway station and bus stand. Perfect for families.',
    type: 'flat',
    listing_type: 'rent',
    price: 16000,
    location: 'Rajajipuram',
    city: 'Lucknow',
    area: 'Rajajipuram',
    bedrooms: 2,
    bathrooms: 1,
    sqft: 850,
    images: [
      'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800',
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
    ],
    amenities: ['parking', 'security', 'wifi'],
    latitude: 26.8300,
    longitude: 80.9100,
    owner_id: 'owner-10',
    owner_name: 'Rajajipuram Properties',
    owner_email: 'rajajipuram@example.com',
    owner_phone: '+91 98765 43219',
    status: 'active',
    featured: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '11',
    title: 'Modern Office Space for Rent in Sector-9',
    description: 'Prime office space in commercial area. Ideal for startups, IT companies, or professional services. Well-connected with parking facilities.',
    type: 'office',
    listing_type: 'rent',
    price: 55000,
    location: 'Sector-9',
    city: 'Lucknow',
    area: 'Vibhuti Khand',
    bedrooms: 0,
    bathrooms: 2,
    sqft: 1200,
    images: [
      'https://images.unsplash.com/photo-1497366754035-f200968a6e72?w=800',
      'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800',
    ],
    amenities: ['parking', 'security', 'wifi', 'elevator'],
    latitude: 26.8800,
    longitude: 80.9700,
    owner_id: 'owner-11',
    owner_name: 'Commercial Realty',
    owner_email: 'commercial@example.com',
    owner_phone: '+91 98765 43220',
    status: 'active',
    featured: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '12',
    title: 'Luxury 5BHK Villa for Sale in Eldeco Colony',
    description: 'Magnificent 5BHK villa with landscaped garden, swimming pool, and premium finishes. Located in upscale neighborhood. Perfect for luxury living.',
    type: 'villa',
    listing_type: 'sale',
    price: 25000000,
    location: 'Eldeco Colony',
    city: 'Lucknow',
    area: 'Indira Nagar',
    bedrooms: 5,
    bathrooms: 4,
    sqft: 4500,
    images: [
      'https://images.unsplash.com/photo-1613977257363-707ba9348227?w=800',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800',
      'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800',
    ],
    amenities: ['parking', 'security', 'garden', 'pool', 'wifi', 'gym', 'servant room'],
    latitude: 26.9000,
    longitude: 80.9900,
    owner_id: 'owner-12',
    owner_name: 'Luxury Homes',
    owner_email: 'luxury@example.com',
    owner_phone: '+91 98765 43221',
    status: 'active',
    featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '13',
    title: '2BHK House for Sale in Chinhat',
    description: 'Beautiful independent 2BHK house with modern amenities. Well-constructed with good ventilation. Close to schools and hospitals. Ready to move.',
    type: 'house',
    listing_type: 'sale',
    price: 4500000,
    location: 'Chinhat',
    city: 'Lucknow',
    area: 'Chinhat',
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1100,
    images: [
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
    ],
    amenities: ['parking', 'security', 'garden', 'wifi'],
    latitude: 26.8200,
    longitude: 80.9400,
    owner_id: 'owner-13',
    owner_name: 'Chinhat Developers',
    owner_email: 'chinhat@example.com',
    owner_phone: '+91 98765 43222',
    status: 'active',
    featured: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '14',
    title: '3BHK Apartment for Rent in Jankipuram',
    description: 'Spacious 3BHK apartment in developing area. Fully furnished with modern appliances. Close to market and public transport. Ideal for families.',
    type: 'flat',
    listing_type: 'rent',
    price: 25000,
    location: 'Jankipuram',
    city: 'Lucknow',
    area: 'Jankipuram',
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1150,
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
      'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
    ],
    amenities: ['parking', 'security', 'elevator', 'wifi'],
    latitude: 26.8100,
    longitude: 80.9200,
    owner_id: 'owner-14',
    owner_name: 'Jankipuram Real Estate',
    owner_email: 'jankipuram@example.com',
    owner_phone: '+91 98765 43223',
    status: 'active',
    featured: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '15',
    title: 'Retail Shop for Sale in Chowk',
    description: 'Prime retail shop in historic Chowk market. High footfall area with excellent visibility. Perfect for business or investment. Legal documents clear.',
    type: 'shop',
    listing_type: 'sale',
    price: 3500000,
    location: 'Chowk',
    city: 'Lucknow',
    area: 'Chowk',
    bedrooms: 0,
    bathrooms: 1,
    sqft: 600,
    images: [
      'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800',
      'https://images.unsplash.com/photo-1445205170230-053b83016050?w=800',
    ],
    amenities: ['parking', 'security'],
    latitude: 26.8600,
    longitude: 80.9200,
    owner_id: 'owner-15',
    owner_name: 'Chowk Traders',
    owner_email: 'chowk@example.com',
    owner_phone: '+91 98765 43224',
    status: 'active',
    featured: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '16',
    title: '4BHK House for Rent in Aliganj',
    description: 'Large 4BHK independent house in residential area. Fully furnished with all modern facilities. Perfect for big families or joint families.',
    type: 'house',
    listing_type: 'rent',
    price: 40000,
    location: 'Aliganj',
    city: 'Lucknow',
    area: 'Aliganj',
    bedrooms: 4,
    bathrooms: 3,
    sqft: 2400,
    images: [
      'https://images.unsplash.com/photo-1600585154084-4e5fe7c39198?w=800',
      'https://images.unsplash.com/photo-1613977257363-707ba9348227?w=800',
    ],
    amenities: ['parking', 'security', 'garden', 'wifi'],
    latitude: 26.8400,
    longitude: 80.9350,
    owner_id: 'owner-16',
    owner_name: 'Aliganj Properties',
    owner_email: 'aliganj@example.com',
    owner_phone: '+91 98765 43225',
    status: 'active',
    featured: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '17',
    title: 'Premium 2BHK Flat for Sale in Sector-14',
    description: 'Well-designed 2BHK apartment in upscale area. Modern architecture with premium finishes. Close to hospitals and shopping malls. Great investment.',
    type: 'flat',
    listing_type: 'sale',
    price: 6800000,
    location: 'Sector-14',
    city: 'Lucknow',
    area: 'Indira Nagar',
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1100,
    images: [
      'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800',
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
    ],
    amenities: ['parking', 'security', 'elevator', 'gym', 'wifi'],
    latitude: 26.8900,
    longitude: 80.9800,
    owner_id: 'owner-17',
    owner_name: 'Sector-14 Developers',
    owner_email: 'sector14@example.com',
    owner_phone: '+91 98765 43226',
    status: 'active',
    featured: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '18',
    title: '1BHK Studio Apartment for Rent in Aminabad',
    description: 'Compact and cozy studio apartment. Fully furnished with all essentials. Perfect for students or single working professionals. Available immediately.',
    type: 'flat',
    listing_type: 'rent',
    price: 10000,
    location: 'Aminabad',
    city: 'Lucknow',
    area: 'Aminabad',
    bedrooms: 1,
    bathrooms: 1,
    sqft: 450,
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
      'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800',
    ],
    amenities: ['parking', 'security', 'wifi'],
    latitude: 26.8381,
    longitude: 80.9236,
    owner_id: 'owner-18',
    owner_name: 'Studio Rentals',
    owner_email: 'studio@example.com',
    owner_phone: '+91 98765 43227',
    status: 'active',
    featured: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '19',
    title: 'Commercial Office Space for Sale in Gomti Nagar',
    description: 'Prime commercial office space in business district. Ideal for corporate offices or professional services. Good investment opportunity with high rental yield.',
    type: 'office',
    listing_type: 'sale',
    price: 12500000,
    location: 'Gomti Nagar',
    city: 'Lucknow',
    area: 'Gomti Nagar',
    bedrooms: 0,
    bathrooms: 3,
    sqft: 2500,
    images: [
      'https://images.unsplash.com/photo-1497366754035-f200968a6e72?w=800',
      'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800',
    ],
    amenities: ['parking', 'security', 'wifi', 'elevator', 'conference room'],
    latitude: 26.8467,
    longitude: 80.9462,
    owner_id: 'owner-19',
    owner_name: 'Business Centers',
    owner_email: 'business@example.com',
    owner_phone: '+91 98765 43228',
    status: 'active',
    featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '20',
    title: '3BHK Villa for Rent in Ashiyana',
    description: 'Beautiful 3BHK villa with private garden. Semi-furnished with modern amenities. Peaceful neighborhood with good connectivity. Perfect for families.',
    type: 'villa',
    listing_type: 'rent',
    price: 50000,
    location: 'Ashiyana',
    city: 'Lucknow',
    area: 'Ashiyana',
    bedrooms: 3,
    bathrooms: 2,
    sqft: 2200,
    images: [
      'https://images.unsplash.com/photo-1613977257363-707ba9348227?w=800',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800',
    ],
    amenities: ['parking', 'security', 'garden', 'wifi'],
    latitude: 26.8000,
    longitude: 80.9500,
    owner_id: 'owner-20',
    owner_name: 'Ashiyana Estates',
    owner_email: 'ashiyana@example.com',
    owner_phone: '+91 98765 43229',
    status: 'active',
    featured: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '21',
    title: '5BHK Independent House for Sale in Mahanagar',
    description: 'Spacious 5BHK independent house with large compound. Modern construction with premium finishes. Ideal for large families. All legal documents verified.',
    type: 'house',
    listing_type: 'sale',
    price: 15000000,
    location: 'Mahanagar',
    city: 'Lucknow',
    area: 'Mahanagar',
    bedrooms: 5,
    bathrooms: 4,
    sqft: 3200,
    images: [
      'https://images.unsplash.com/photo-1600585154084-4e5fe7c39198?w=800',
      'https://images.unsplash.com/photo-1600607687644-c7171b42498b?w=800',
      'https://images.unsplash.com/photo-1613977257363-707ba9348227?w=800',
    ],
    amenities: ['parking', 'security', 'garden', 'wifi', 'servant room'],
    latitude: 26.8500,
    longitude: 80.9300,
    owner_id: 'owner-21',
    owner_name: 'Mahanagar Builders',
    owner_email: 'mahanagar@example.com',
    owner_phone: '+91 98765 43230',
    status: 'active',
    featured: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '22',
    title: '2BHK Flat for Rent in Sector-H',
    description: 'Comfortable 2BHK apartment in well-maintained society. Close to schools and hospitals. Good security and facilities. Perfect for small families.',
    type: 'flat',
    listing_type: 'rent',
    price: 19000,
    location: 'Sector-H',
    city: 'Lucknow',
    area: 'Aliganj',
    bedrooms: 2,
    bathrooms: 2,
    sqft: 950,
    images: [
      'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800',
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
    ],
    amenities: ['parking', 'security', 'elevator', 'wifi'],
    latitude: 26.8450,
    longitude: 80.9320,
    owner_id: 'owner-22',
    owner_name: 'Sector-H Properties',
    owner_email: 'sectorh@example.com',
    owner_phone: '+91 98765 43231',
    status: 'active',
    featured: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '23',
    title: 'Shop for Rent in Faizabad Road',
    description: 'Prime location shop on main road. High visibility and footfall. Suitable for retail, showroom, or restaurant. Good parking space available.',
    type: 'shop',
    listing_type: 'rent',
    price: 35000,
    location: 'Faizabad Road',
    city: 'Lucknow',
    area: 'Faizabad Road',
    bedrooms: 0,
    bathrooms: 1,
    sqft: 800,
    images: [
      'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800',
      'https://images.unsplash.com/photo-1445205170230-053b83016050?w=800',
    ],
    amenities: ['parking', 'security'],
    latitude: 26.8700,
    longitude: 80.9400,
    owner_id: 'owner-23',
    owner_name: 'Faizabad Road Commercial',
    owner_email: 'faizabad@example.com',
    owner_phone: '+91 98765 43232',
    status: 'active',
    featured: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '24',
    title: '4BHK Apartment for Sale in Sector-2',
    description: 'Luxurious 4BHK apartment with premium amenities. Spacious interiors with modern design. Close to IT hub and educational institutions. Great investment.',
    type: 'flat',
    listing_type: 'sale',
    price: 12500000,
    location: 'Sector-2',
    city: 'Lucknow',
    area: 'Gomti Nagar Extension',
    bedrooms: 4,
    bathrooms: 3,
    sqft: 1850,
    images: [
      'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800',
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
    ],
    amenities: ['parking', 'security', 'elevator', 'gym', 'pool', 'wifi', 'clubhouse'],
    latitude: 26.8650,
    longitude: 80.9550,
    owner_id: 'owner-24',
    owner_name: 'Sector-2 Developers',
    owner_email: 'sector2@example.com',
    owner_phone: '+91 98765 43233',
    status: 'active',
    featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '25',
    title: '3BHK House for Rent in Telibagh',
    description: 'Well-maintained 3BHK house in residential area. Fully furnished with all amenities. Close to market and schools. Perfect for families.',
    type: 'house',
    listing_type: 'rent',
    price: 28000,
    location: 'Telibagh',
    city: 'Lucknow',
    area: 'Telibagh',
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1400,
    images: [
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
    ],
    amenities: ['parking', 'security', 'garden', 'wifi'],
    latitude: 26.7900,
    longitude: 80.9100,
    owner_id: 'owner-25',
    owner_name: 'Telibagh Properties',
    owner_email: 'telibagh@example.com',
    owner_phone: '+91 98765 43234',
    status: 'active',
    featured: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '26',
    title: 'Premium Office Space for Rent in Sector-8',
    description: 'Modern office space in commercial complex. Fully air-conditioned with modern facilities. Ideal for corporate offices, startups, or professional services.',
    type: 'office',
    listing_type: 'rent',
    price: 60000,
    location: 'Sector-8',
    city: 'Lucknow',
    area: 'Vibhuti Khand',
    bedrooms: 0,
    bathrooms: 2,
    sqft: 1500,
    images: [
      'https://images.unsplash.com/photo-1497366754035-f200968a6e72?w=800',
      'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800',
    ],
    amenities: ['parking', 'security', 'wifi', 'elevator', 'air conditioning'],
    latitude: 26.8750,
    longitude: 80.9650,
    owner_id: 'owner-26',
    owner_name: 'Office Spaces Ltd',
    owner_email: 'offices@example.com',
    owner_phone: '+91 98765 43235',
    status: 'active',
    featured: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '27',
    title: 'Luxury 4BHK Villa for Rent in Eldeco',
    description: 'Stunning 4BHK villa with private pool and landscaped garden. Fully furnished with premium furniture and modern appliances. Perfect for luxurious living.',
    type: 'villa',
    listing_type: 'rent',
    price: 90000,
    location: 'Eldeco Colony',
    city: 'Lucknow',
    area: 'Indira Nagar',
    bedrooms: 4,
    bathrooms: 3,
    sqft: 3800,
    images: [
      'https://images.unsplash.com/photo-1613977257363-707ba9348227?w=800',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800',
      'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800',
    ],
    amenities: ['parking', 'security', 'garden', 'pool', 'wifi', 'gym', 'servant room'],
    latitude: 26.9000,
    longitude: 80.9900,
    owner_id: 'owner-27',
    owner_name: 'Luxury Rentals',
    owner_email: 'luxuryrent@example.com',
    owner_phone: '+91 98765 43236',
    status: 'active',
    featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '28',
    title: '2BHK House for Sale in Aashiana',
    description: 'Compact 2BHK independent house. Well-constructed with good facilities. Close to all amenities. Perfect for small families or investment.',
    type: 'house',
    listing_type: 'sale',
    price: 3800000,
    location: 'Aashiana',
    city: 'Lucknow',
    area: 'Aashiana',
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1000,
    images: [
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
    ],
    amenities: ['parking', 'security', 'garden', 'wifi'],
    latitude: 26.8000,
    longitude: 80.9500,
    owner_id: 'owner-28',
    owner_name: 'Aashiana Homes',
    owner_email: 'aashiana@example.com',
    owner_phone: '+91 98765 43237',
    status: 'active',
    featured: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

// Mock user data
export const mockUsers = [
  {
    id: 'user-1',
    email: 'demo@example.com',
    full_name: 'Demo User',
    phone: '+91 98765 43210',
    role: 'user' as const,
    avatar_url: null,
    created_at: new Date().toISOString(),
  },
  {
    id: 'admin-1',
    email: 'admin@example.com',
    full_name: 'Admin User',
    phone: '+91 98765 43200',
    role: 'admin' as const,
    avatar_url: null,
    created_at: new Date().toISOString(),
  },
]

// Check if Supabase is configured
export const isSupabaseConfigured = () => {
  return !!(
    process.env.NEXT_PUBLIC_SUPABASE_URL &&
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY &&
    process.env.NEXT_PUBLIC_SUPABASE_URL !== 'your_supabase_project_url'
  )
}
